# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Timepill' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  
  # Pods for Timepill
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'
  
  target 'TimepillTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Timepill-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Timepill-tvOS

  target 'Timepill-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
