export default {
About: require("./AboutPage.js").default,
BlockUser: require("./BlockUserPage.js").default,
DiaryDetail: require("./DiaryDetailPage.js").default,
Empty: require("./EmptyPage.js").default,
Feedback: require("./FeedbackPage.js").default,
Follow: require("./FollowPage.js").default,
FollowUser: require("./FollowUserPage.js").default,
Home: require("./HomePage.js").default,
NotebookDetail: require("./NotebookDetailPage.js").default,
NotebookEdit: require("./NotebookEditPage.js").default,
NotebookMerge: require("./NotebookMergePage.js").default,
NotificationHistory: require("./NotificationHistoryPage.js").default,
Notification: require("./NotificationPage.js").default,
Password: require("./PasswordPage.js").default,
Photo: require("./PhotoPage.js").default,
Setting: require("./SettingPage.js").default,
Topic: require("./TopicPage.js").default,
UserInfoEdit: require("./UserInfoEditPage.js").default,
UserIntroEdit: require("./UserIntroEditPage.js").default,
UserNameEdit: require("./UserNameEditPage.js").default,
User: require("./UserPage.js").default,
WebView: require("./WebViewPage.js").default,
Write: require("./WritePage.js").default
}